packages:
  - packages/*
  - "!**/test/**"
catalog:
  globals: ^16.3.0
  eslint: ^9.21.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react-refresh: ^0.4.19
  prettier: ^3.6.2
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.7.3
  typescript-eslint: ^8.25.0
  uuid: ^11.1.0
  vitest: ^3.2.4
  vite: ^7.0.0
  zustand: "^5.0.3"
  "@eslint/js": ^9.21.0
  "@vitejs/plugin-react": ^4.6.0
  "@tari-project/tarijs-all": ^0.13.0
  "@tari-project/typescript-bindings": ^1.15.0
  "@tari-project/wallet-connect-signer": ^0.13.0
  "@tari-project/wallet-daemon-signer": ^0.13.0
  "@types/node": ^24.0.8
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@types/vscode": ^1.74.0
  "@types/vscode-webview": ^1.57.5
