name: Publish Extension

on:
  workflow_run:
    workflows: ["Publish Query Builder Package to npmjs"]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true

      - name: Install dependencies
        run: pnpm install

      - name: Build the extension
        run: moon tari-extension:build

      - name: Publish to VS Code Marketplace
        run: bash ./scripts/vscode_publish.sh
        working-directory: packages/tari-extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
