name: Publish JSON Schema to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate JSON Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true
      - run: pnpm install
      - name: Generate JSON Schema
        run: moon tari-extension-query-builder:generate-schema
      - name: Copy schema to artifact folder
        run: |
          mkdir -p schemas
          cp packages/tari-extension-query-builder/schemas/*.json schemas/
      - name: Upload Schema Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: schemas

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: schemas
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
      - name: List files after artifact download
        run: |
          pwd
          ls -lR
          ls -l schemas
          ls schemas/*.json || echo 'No JSON schemas found'
      - name: Check if schema changed
        id: schema_diff
        run: |
          mkdir -p gh-pages/schemas
          set -e
          SCHEMA_FILE=$(ls schemas/*.json | head -n1)
          SCHEMA_BASENAME=$(basename "$SCHEMA_FILE")
          GH_PAGES_SCHEMA="gh-pages/schemas/$SCHEMA_BASENAME"
          if [ -f "$GH_PAGES_SCHEMA" ]; then
            if diff -q "$SCHEMA_FILE" "$GH_PAGES_SCHEMA" > /dev/null; then
              echo "Schema unchanged. Skipping publish."
              echo "skip_publish=true" >> $GITHUB_OUTPUT
            else
              cp -f "$SCHEMA_FILE" "$GH_PAGES_SCHEMA"
              echo "skip_publish=false" >> $GITHUB_OUTPUT
            fi
          else
            cp -f "$SCHEMA_FILE" "$GH_PAGES_SCHEMA"
            echo "skip_publish=false" >> $GITHUB_OUTPUT
          fi
      - name: Commit and push changes
        if: steps.schema_diff.outputs.skip_publish == 'false'
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add schemas/*.json
          git commit -m "Update latest JSON schema" || echo "No changes to commit"
          git push origin gh-pages
      - name: Deploy to GitHub Pages
        if: steps.schema_diff.outputs.skip_publish == 'false'
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Skip deploy (schema unchanged)
        if: steps.schema_diff.outputs.skip_publish == 'true'
        run: echo "Schema unchanged, skipping deploy."
